### ISSUE TITLE
pnpm run build is failing

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#8] opened 2024-07-25 21:43 UTC
"pnpm run build" is failing.
do you have local changes not checked in?

**Comment by gopal-vsg** [comment] 2024-07-26 05:30
Sir I tried using pnpm run build in my computer at it is working. I’ve confirmed that all the local changes are committed to the Repo and it's up to date. Please elaborate the error you are facing, and I'll try to make changes if possible.

![image](https://github.com/user-attachments/assets/82befdd4-e8f7-4cbb-ab55-067f0338960f)

![image](https://github.com/user-attachments/assets/6b47aeb3-1024-4b59-b909-9bd4fc1db169)

I'll make a git push again, let me know if the issue is not resolved.

**Comment by gopal-vsg** [comment] 2024-07-26 12:17
Sir I followed the steps you mentioned
Deleted the local repo, cloned it again from GitHub, and then ran pnpm install and pnpm run build. 
The Supabase package issue has been resolved. Now you can find the supabase dependencies in package.json and pnpm-lock.yaml,
I hope `pnpm run build` will work fine now.

**Closed as completed by gopal-vsg** 2024-07-26 12:17 UTC
